# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile

db.default.driver=com.mysql.cj.jdbc.Driver
db.default.url="jdbc:mysql://localhost:3306/expense_tracker"
db.default.username="root"
db.default.password="Password"

play.filters.disabled += "play.filters.csrf.CSRFFilter"
